version: "3.3"

services:
  frontend:
    image: intkbv/rietveld-frontend:sha-f2f40b6
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_GA4_CODE: "G-33ERDL4GY0"
    depends_on:
      - backend
    networks:
      - backend
    ports:
      - 3000:3000
    deploy:
      replicas: 2

  stage-frontend:
    image: intkbv/rietveld-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_GA4_CODE: "G-33ERDL4GY0"
    depends_on:
      - backend
    networks:
      - backend
    ports:
      - 3001:3000
    deploy:
      replicas: 1

  backend:
    image: intkbv/rietveld-backend:sha-fdfdeec
    environment:
      SITE: Plone
    volumes:
      - site-data:/data
    networks:
      - backend
    ports:
      - 8080:8080

volumes:
  site-data:
    driver_opts:
      type: none
      device: /srv/rietveld/data
      o: bind

networks:
  backend:
    driver: overlay
